import test from "node:test";
import assert from "node:assert/strict";
import { decodeGenerate, GENERATE_OPS } from "../tools/wire.js";
import { dungeonFloorGenerate, playerOwnerGenerate } from "../src/socket/objects.js";
import { buildFloor } from "./helpers/floor.js";

const TUTORIAL = "castle/arena/db_floor_TUTORIAL_LEVEL_1.json";

/**
 * The decoder that keeps the comparisons honest.
 *
 * Four claims about the captures were made and withdrawn in a single sitting —
 * a gargoyle firing the wrong attack, a hero re-minted on every floor, mines
 * armed the wrong way round, thirteen actors that did not exist. All four came
 * from throwaway scripts counting bytes by eye, and all four were plausible
 * enough to survive being read twice.
 *
 * What they had in common is that none of them could fail loudly. A generate is
 * a closed frame, so a decoder that tracks its own cursor can say whether it
 * understood one; these tests hold that property rather than any particular
 * field value.
 */

test("every generate this server sends is read back exactly", async () => {
  const world = await buildFloor(TUTORIAL);

  let read = 0;
  for (const frame of world.frames) {
    const body = frame.body;
    if (body.length < 16 || !GENERATE_OPS.has(body.readUInt16LE(0))) continue;
    const decoded = decodeGenerate(body);
    assert.equal(decoded.error, undefined, `${decoded.class ?? decoded.clid}: ${decoded.error}`);
    assert.equal(
      decoded.trailing,
      0,
      `${decoded.class} left ${decoded.trailing} byte(s) unaccounted for`
    );
    read += 1;
  }
  assert.ok(read > 50, `only ${read} generates decoded`);
});

test("a floor generate carries its layout back out intact", async () => {
  /**
   * Not a byte test — a meaning test. If the decoder can name the fields then
   * the layout it used was the class's own, and a diff against a capture can
   * compare `heading` with `heading` rather than offset 22 with offset 22.
   *
   * The floor object itself is generated by `enterDungeon` rather than by
   * `buildFloorWorld`, which builds what stands on it, so it is written here
   * directly from the same builder the server uses.
   */
  const world = await buildFloor(TUTORIAL);
  const tiles = world.floor.tiles.map(({ x, y, tileId }) => ({ x, y, tileId }));

  const decoded = decodeGenerate(
    dungeonFloorGenerate({
      doid: 1002,
      parent: 1,
      mapNodeId: 50002,
      tierConstant: "CASTLE_TIER1",
      floor: world.floor,
      tiles,
    }).subarray(2)
  );

  assert.equal(decoded.error, undefined, decoded.error);
  assert.equal(decoded.trailing, 0, "the floor's own fields account for the frame");
  assert.equal(decoded.class, "DistributedDungeonFloor");
  assert.equal(decoded.fields.tileLibrary, world.floor.tileLibrary);
  assert.equal(decoded.fields.tiles.length, tiles.length, "every tile survives the round trip");
  for (const [index, [x, y, tileId]] of decoded.fields.tiles.entries()) {
    assert.deepEqual({ x, y, tileId }, tiles[index], `tile ${index} came back changed`);
  }
});

test("an npc generate decodes to the fields the diff compares", async () => {
  const world = await buildFloor(TUTORIAL);

  const npcs = world.frames
    .map((frame) => frame.body)
    .filter((body) => body.length >= 16 && GENERATE_OPS.has(body.readUInt16LE(0)))
    .map(decodeGenerate)
    .filter((decoded) => decoded.class === "DistributedNPCGameObject");

  assert.ok(npcs.length > 50, `only ${npcs.length} npcs`);
  for (const npc of npcs) {
    const f = npc.fields;
    assert.equal(f.position.length, 2, "position is a pair");
    assert.equal(f.weaponDetails.length, 4, "four weapon slots, always");
    assert.ok([1, 5, 6, 7].includes(f.team), `team ${f.team} is not one the game uses`);
    assert.ok(f.remoteTriggerState === 0 || f.remoteTriggerState === 1);
  }
});

test("a damaged frame is reported rather than guessed at", async () => {
  /**
   * The property the whole tool rests on: a decoder that cannot tell a good
   * frame from a bad one turns every mistake into a measurement.
   *
   * Spare bytes are not simply counted, because the protocol says what they
   * are. `DcNetworkClass.recvByIdLoop` reads a count and then field-id/value
   * pairs until the frame ends, so three stray bytes are a malformed trailing
   * block and are named as one.
   */
  const world = await buildFloor(TUTORIAL);
  const body = world.frames
    .map((frame) => frame.body)
    .find((b) => b.length >= 16 && GENERATE_OPS.has(b.readUInt16LE(0)) &&
      decodeGenerate(b).class === "DistributedNPCGameObject");

  assert.ok(body, "found one to damage");

  const short = decodeGenerate(body.subarray(0, body.length - 1));
  assert.ok(short.error || short.trailing !== 0, "a truncated frame does not read as clean");

  const long = decodeGenerate(Buffer.concat([body, Buffer.alloc(3)]));
  assert.ok(long.error, `spare bytes are rejected, not counted: ${JSON.stringify(long)}`);
});

test("an owner generate round-trips through the same decoder", async () => {
  /**
   * Opcode 136 leads with the class id where 134 and 135 lead with the parent,
   * and it was excluded from this decoder entirely — so the two objects the
   * player owns, the ones every session depends on, were outside every wire
   * test while the report still said 100%.
   */
  const owner = decodeGenerate(
    playerOwnerGenerate({
      doid: 500, parent: 1, zone: 10, screenName: "Asimetra", basicCurrency: 12345,
    }).subarray(2)
  );

  assert.equal(owner.error, undefined, owner.error);
  assert.equal(owner.op, 136);
  assert.equal(owner.class, "PlayerGameObjectOwner");
  assert.equal(owner.clid, 29, "read from the owner header, not the visible one");
  assert.equal(owner.doid, 500);
  assert.equal(owner.fields.screenName, "Asimetra");
  assert.equal(owner.fields.basicCurrency, 12345, "typed from the owner component's reader");
  assert.equal(owner.trailing, 0);
});
