/**
 * One decoder for object generates, driven by the schema instead of by hand.
 *
 * Every wrong claim this repository has made about the captures came from the
 * same place: a throwaway script with an offset counted by eye. Four in one
 * sitting — a gargoyle firing the wrong attack, a hero re-minted on every
 * floor, mines armed the wrong way round, thirteen actors that did not exist.
 * Each read a field from a position that was right for one opcode and wrong for
 * another, and each looked like a finding because the numbers that came back
 * were plausible.
 *
 * The fix is not to be more careful. It is to make the decoder say when it is
 * wrong. A generate is a closed frame: header, then exactly the fields the
 * class names in its `generate` list, then nothing. So a decode that does not
 * land precisely on the end of the frame is a decode that misread something,
 * and `trailing` reports it. Any measurement built on this can be checked by
 * asking what fraction of frames closed cleanly — see `--validate`.
 *
 *   node tools/wire.js --validate <logs-dir> [<logs-dir> ...]
 *
 * The types come from docs/dc-schema.json, which is generated by dc-schema.js
 * from the client's own generated network components:
 *
 *   u8 i8 u16 u32 i32 f32 utf     one value
 *   Struct{...} with repeat N     N records back to back
 *   u16 Struct{...}               a byte-length-prefixed list of records
 */
import fs from "node:fs";
import path from "node:path";
import readline from "node:readline";
import { fileURLToPath } from "node:url";
import { CLID } from "../src/socket/opcodes.js";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const schema = JSON.parse(fs.readFileSync(path.join(root, "docs", "dc-schema.json"), "utf8"));

/**
 * Three opcodes carry a generate, and one of them has a different header.
 *
 * 134 and 135 lead with the parent and the zone; 136 — the owner's own copy of
 * an object — leads with the class id. Read with the visible header its class
 * id lands on a halfword that runs 762..821 across the corpus, which is no
 * class at all, and that is what made this file call it "not a generate" for a
 * while. Read with its own header the same field is 28 or 29 and nothing else,
 * across 296 official frames and 226 of ours: HeroGameObject and
 * PlayerGameObject, the two objects the player owns.
 */
export const GENERATE_OPS = new Set([134, 135, 136]);

/** Header layouts, by opcode. Each returns the fixed part and its length. */
const HEADERS = {
  visible: (body) => ({
    parent: body.readUInt32LE(2),
    zone: body.readUInt32LE(6),
    clid: body.readUInt16LE(10),
    doid: body.readUInt32LE(12),
    length: 16,
  }),
  owner: (body) => ({
    clid: body.readUInt16LE(2),
    doid: body.readUInt32LE(4),
    parent: body.readUInt32LE(8),
    zone: body.readUInt32LE(12),
    length: 16,
  }),
};

/**
 * Which schema class an opcode/class-id pair names.
 *
 * The same class id means a different object depending on who it is for: 28
 * over opcode 134 is another player's hero, and over 136 it is your own, which
 * carries eight more required fields — the consumables, the buster points, the
 * two powerup slots. Keying only on the class id reads the owner's copy as a
 * visible one and stops eight fields short.
 */
const OWNER_CLASS = { 28: "HeroGameObjectOwner", 29: "PlayerGameObjectOwner" };

/**
 * What follows the required block, straight out of `DcNetworkClass`:
 *
 *   recvByIdLoop(packet):
 *     if (!eof) {
 *       count = readUnsignedShort();
 *       while (!eof) { id = readUnsignedShort(); recvById(packet, id); }
 *     }
 *
 * So a generate is the required fields and then, *only if any bytes remain*, a
 * count followed by field-id/value pairs until the frame ends. It is not a
 * property of the opcode: op 134 frames in these corpora simply end on their
 * required block, and op 135 frames carry the count with no pairs after it —
 * which is the two trailing bytes this file used to special-case by opcode.
 *
 * Reading it properly is what lets `PlayerGameObjectOwner` close: its
 * `basicCurrency` is not a required field at all — the client has no
 * `recv_basicCurrency` — it arrives here, as field 181.
 */
const readTrailingFields = (reader, definition, body, headerBytes, fields) => {
  if (headerBytes + reader.at >= body.length) return;
  reader.primitive("u16"); // the count, which the client reads and then ignores
  while (headerBytes + reader.at < body.length) {
    const id = reader.primitive("u16");
    const field = fieldById(definition, id);
    if (!field) throw new TypeError(`no field ${id} on ${definition.class} or its base`);
    fields[field.name] = readField(reader, field);
  }
};

/**
 * A class names fields it inherits, so the lookup has to reach past its own
 * list — `HeroGameObjectOwner.generate` names twelve fields that live on
 * `HeroGameObject`, and treating those as missing is what made the owner hero
 * undecodable and left it out of every census.
 */
const fieldByName = new Map();
for (const definition of Object.values(schema.classes)) {
  for (const field of definition.fields ?? []) {
    if (!fieldByName.has(field.name)) fieldByName.set(field.name, field);
  }
}

/** Class name -> its description, for the owner classes the clid cannot name. */
const byName = new Map(Object.values(schema.classes).map((d) => [d.class, d]));

/**
 * A field, resolved through the class that names it rather than by name alone.
 *
 * `hitPoints` is a `u32` on an NPC and a `u16` on a hero, so a global
 * first-match lookup is a coin toss that happens to have been landing right.
 * It stops being harmless the moment the owner hero is decoded, because
 * `HeroGameObjectOwner` declares nothing itself and inherits its whole generate
 * block: every one of those twenty fields would be resolved by name.
 *
 * The schema does not carry `extends`, so the relationship is taken from the
 * name — an `XOwner` is an `X` with more — and only then does it fall back to
 * the global map, which now covers a shrinking remainder.
 */
const fieldById = (definition, id) => {
  const own = definition.fields?.find((f) => Number(f.id) === id);
  if (own) return own;
  const base = byName.get(definition.class.replace(/Owner$/, ""));
  return base?.fields?.find((f) => Number(f.id) === id) ?? null;
};

const fieldFor = (definition, name) => {
  const own = definition.fields?.find((f) => f.name === name);
  if (own) return own;
  const base = byName.get(definition.class.replace(/Owner$/, ""));
  const inherited = base?.fields?.find((f) => f.name === name);
  return inherited ?? fieldByName.get(name);
};

/** Wire class id -> the schema's description of it, by name. */
const byClid = new Map();
for (const definition of Object.values(schema.classes)) {
  const clid = CLID[definition.class];
  if (clid !== undefined) byClid.set(clid, definition);
}

const PRIMITIVE = {
  u8: [1, (b, at) => b.readUInt8(at)],
  i8: [1, (b, at) => b.readInt8(at)],
  u16: [2, (b, at) => b.readUInt16LE(at)],
  i16: [2, (b, at) => b.readInt16LE(at)],
  u32: [4, (b, at) => b.readUInt32LE(at)],
  i32: [4, (b, at) => b.readInt32LE(at)],
  f32: [4, (b, at) => b.readFloatLE(at)],
};

/** Reader over one frame body that refuses to run past the end. */
const readerFor = (body) => {
  let at = 0;
  const need = (bytes) => {
    if (at + bytes > body.length) throw new RangeError(`short frame at ${at}+${bytes}/${body.length}`);
  };
  return {
    get at() { return at; },
    primitive(type) {
      const [size, read] = PRIMITIVE[type];
      need(size);
      const value = read(body, at);
      at += size;
      return value;
    },
    utf() {
      need(2);
      const length = body.readUInt16LE(at);
      at += 2;
      need(length);
      const text = body.toString("utf8", at, at + length);
      at += length;
      return text;
    },
    record(types) {
      const out = [];
      for (const type of types) {
        if (type === "utf") out.push(this.utf());
        else if (PRIMITIVE[type]) out.push(this.primitive(type));
        else out.push(...this.record(typesOf(type)));
      }
      return out;
    },
    /** Everything inside the next `u16` bytes, however many records that is. */
    list(types) {
      need(2);
      const bytes = body.readUInt16LE(at);
      at += 2;
      const end = at + bytes;
      if (end > body.length) throw new RangeError(`list of ${bytes}B runs past the frame`);
      const out = [];
      while (at < end) out.push(this.record(types));
      if (at !== end) throw new RangeError("list records do not fill their declared bytes");
      return out;
    },
  };
};

const STRUCT = /^([A-Za-z]\w*)\{([^}]*)\}$/;

/**
 * A struct's fields, with nested structs resolved.
 *
 * The extractor renders a struct inside a struct as `Attack{?}`, because it
 * reads one class at a time. The pieces are all there — `Attack` is
 * `i8 u8 u32 u32` and `CombatResult` names it — so the `?` is a join that was
 * never done rather than something unknown. Resolved here, `CombatResult`
 * comes to 37 bytes, which is the stride every hand-written reader in this
 * repository had already measured off the wire.
 */
const structTypes = (name, seen = new Set()) => {
  if (seen.has(name)) throw new TypeError(`struct ${name} contains itself`);
  const reads = schema.structs?.[name];
  if (!reads) throw new TypeError(`no struct named ${name}`);
  const out = [];
  for (const read of reads) {
    const nested = STRUCT.exec(read);
    out.push(...(nested ? structTypes(nested[1], new Set([...seen, name])) : [read]));
  }
  return out;
};

/**
 * The types a `Name{...}` token stands for.
 *
 * Resolved by name rather than by reading the braces, because the braces nest:
 * `CombatResult{u32 u32 i32 Attack{?} …}` has a `}` in the middle of it, and a
 * pattern that stops at the first one fails to match the token at all — which
 * left the reader handing itself the same string forever.
 */
const typesOf = (token) => {
  const named = /^([A-Za-z]\w*)\{/.exec(token);
  if (!named) return [token];
  return structTypes(named[1]);
};

/** One field, as its `reads` and `repeat` describe it. */
const readField = (reader, field) => {
  const reads = field.layout?.reads;
  /**
   * A field the extractor could not type is not a zero-length field.
   *
   * `PlayerGameObject.basicCurrency` came through with no `reads` at all, and
   * reading nothing for it left four bytes of every owner generate unexplained
   * while the frame still looked *nearly* right. Silence here is the failure
   * this decoder exists to prevent, so it is an error with the field's name on it.
   */
  if (!reads) throw new TypeError(`field "${field.name}" has no layout in the schema`);
  const repeat = Number(field.layout?.repeat ?? 1);

  // `u16 Struct{...}` and `u16 u32` are both byte-length-prefixed lists.
  if (reads.length === 2 && reads[0] === "u16") return reader.list(typesOf(reads[1]));

  const out = [];
  for (let n = 0; n < repeat; n += 1) {
    for (const read of reads) {
      if (read === "utf") out.push(reader.utf());
      else if (PRIMITIVE[read]) out.push(reader.primitive(read));
      else out.push(reader.record(typesOf(read)));
    }
  }
  return repeat === 1 && out.length === 1 ? out[0] : out;
};

/**
 * A generate, or why it could not be read.
 *
 * `trailing` is the whole point: zero means the class's own field list
 * accounted for every byte, and anything else means this decoder and the
 * client disagree about the shape of the frame.
 */
export const decodeGenerate = (body) => {
  if (body.length < 16) return { error: "shorter than a generate header" };
  const op = body.readUInt16LE(0);
  if (!GENERATE_OPS.has(op)) return { error: `op ${op} is not a generate` };

  const { length: headerBytes, ...head } = HEADERS[op === 136 ? "owner" : "visible"](body);
  head.op = op;

  const definition =
    op === 136 ? byName.get(OWNER_CLASS[head.clid]) ?? byClid.get(head.clid) : byClid.get(head.clid);
  if (!definition) return { ...head, error: `no schema for clid ${head.clid} under op ${op}` };

  const reader = readerFor(body.subarray(headerBytes));
  const fields = {};
  try {
    for (const name of definition.generate ?? []) {
      const field = fieldFor(definition, name);
      if (!field) return { ...head, error: `no field "${name}" on ${definition.class}` };
      fields[name] = readField(reader, field);
    }
    readTrailingFields(reader, definition, body, headerBytes, fields);
  } catch (error) {
    return { ...head, class: definition.class, error: error.message };
  }

  return {
    ...head,
    class: definition.class,
    fields,
    trailing: body.length - headerBytes - reader.at,
  };
};

/**
 * One `CLIENT_OBJECT_UPDATE_FIELD`, read against the class that owns the doid.
 *
 * The caller keeps the doid-to-class map, because only the generates say what
 * an object is. Everything else is the same discipline as a generate: the field
 * is looked up by id through the class and its base, its layout says how to
 * read it, and whatever is left over is reported rather than ignored.
 *
 * This exists so the corpus tools stop counting bytes by hand. Every wrong
 * claim in this repository came from a script doing that, and the ones about
 * ordered behaviour — when a trap fires, who it hit, how long the shot took —
 * need field payloads, not just generates.
 */
export const decodeFieldUpdate = (body, definition) => {
  if (body.length < 8 || body.readUInt16LE(0) !== 124) return { error: "not a field update" };
  const doid = body.readUInt32LE(2);
  const id = body.readUInt16LE(6);
  if (!definition) return { doid, id, error: "no class known for this doid" };

  const field = fieldById(definition, id);
  if (!field) return { doid, id, error: `no field ${id} on ${definition.class}` };
  if (!field.layout?.reads) return { doid, id, name: field.name, error: "field has no layout" };

  const reader = readerFor(body.subarray(8));
  try {
    const value = readField(reader, field);
    return { doid, id, name: field.name, value, trailing: body.length - 8 - reader.at };
  } catch (error) {
    return { doid, id, name: field.name, error: error.message };
  }
};

/** The schema's description of a wire class id, for the doid map a caller keeps. */
export const classForClid = (clid) => byClid.get(clid) ?? null;

/** Schema description by class name, including owner subclasses. */
export const classForName = (name) => byName.get(name) ?? null;

/**
 * Every frame of a capture, with enough of its record to judge it.
 *
 * `truncated` is the record's own answer, not a guess from its size. The old
 * client's logger caps its hex at 512 bytes and writes the real length beside
 * it; this server's capture writer stores frames whole. Treating 512 as the
 * cut discarded 64 complete local generates — and those are the big ones, the
 * floors with their whole tile layout, which is precisely the payload most
 * worth checking.
 */
export const framesOf = async function* (file) {
  const lines = readline.createInterface({ input: fs.createReadStream(file), crlfDelay: Infinity });
  for await (const line of lines) {
    if (!line.trim()) continue;
    let record;
    try { record = JSON.parse(line); } catch { continue; }
    const body = Buffer.from(record.hex ?? "", "hex");
    if (body.length < 2) continue;
    const declared = Number(record.len);
    yield {
      body,
      out: record.dir === "out",
      /**
       * Carried because cadence is a question the corpus can answer, and it is
       * not a field in any frame — how often a thing swings is the gap between
       * two of them.
       *
       * It is the *client's* clock. Every capture here was written by the
       * client, so an outbound frame is stamped when it was sent and an inbound
       * one when it arrived: any "the server answered in X" measured across the
       * two contains a full round trip. The official's is 143ms at the median
       * and 167 at p90, over 3914 request/response pairs — the hero proposing a
       * hit and the server echoing it back priced — and it sits near 140 in
       * every capture but one.
       *
       * Two conclusions have already been drawn from this timeline without
       * subtracting that, and both were wrong: a 208ms projectile rewind that
       * the official does not do, and a 200ms proximity-trigger clock that is
       * simply the phase between a 208ms position stream and a 143ms link.
       * Gaps between two frames in the same direction are safe. Anything that
       * crosses is not.
       */
      at: Date.parse(record.ts),
      truncated: Number.isFinite(declared) ? body.length < declared : null,
    };
  }
};

const validate = async (directories) => {
  const tally = new Map();
  let truncated = 0;

  for (const directory of directories) {
    const captures = fs
      .readdirSync(directory)
      .filter((name) => name.startsWith("socket-") && name.endsWith(".jsonl"))
      .sort();
    for (const capture of captures) {
      for await (const { body, truncated: cut } of framesOf(path.join(directory, capture))) {
        if (!GENERATE_OPS.has(body.readUInt16LE(0))) continue;
        if (cut) { truncated += 1; continue; }
        const decoded = decodeGenerate(body);
        const key = `op${decoded.op} ${decoded.class ?? `clid ${decoded.clid}`}`;
        const seen = tally.get(key) ?? { clean: 0, trailing: new Map(), failed: new Map() };
        if (decoded.error) seen.failed.set(decoded.error, (seen.failed.get(decoded.error) ?? 0) + 1);
        else if (decoded.trailing === 0) seen.clean += 1;
        else seen.trailing.set(decoded.trailing, (seen.trailing.get(decoded.trailing) ?? 0) + 1);
        tally.set(key, seen);
      }
    }
    console.log(`read ${captures.length} capture(s) from ${directory}`);
  }

  console.log("\n  frames   clean  trailing bytes / failure");
  let clean = 0;
  let dirty = 0;
  for (const [key, seen] of [...tally].sort((a, b) => {
    const total = (s) => s.clean + [...s.trailing.values()].reduce((x, y) => x + y, 0) + [...s.failed.values()].reduce((x, y) => x + y, 0);
    return total(b[1]) - total(a[1]);
  })) {
    const off = [...seen.trailing].sort((a, b) => b[1] - a[1]);
    const bad = [...seen.failed].sort((a, b) => b[1] - a[1]);
    const total = seen.clean + off.reduce((x, [, n]) => x + n, 0) + bad.reduce((x, [, n]) => x + n, 0);
    clean += seen.clean;
    dirty += total - seen.clean;
    const notes = [
      ...off.map(([bytes, n]) => `${n}x left ${bytes}B over`),
      ...bad.map(([why, n]) => `${n}x ${why}`),
    ];
    console.log(
      `  ${String(total).padStart(6)}  ${String(seen.clean).padStart(6)}  ${key}` +
        (notes.length ? `\n${notes.map((n) => `                  ${n}`).join("\n")}` : "")
    );
  }

  console.log(
    `\n${clean} of ${clean + dirty} generates closed exactly on the end of their frame` +
      ` (${((100 * clean) / Math.max(1, clean + dirty)).toFixed(1)}%).`
  );
  if (truncated) {
    console.log(`${truncated} frame(s) skipped: the capture recorded less hex than the frame's declared length.`);
  }
};

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const directories = process.argv.slice(2).filter((a) => !a.startsWith("--"));
  if (!process.argv.includes("--validate") || !directories.length) {
    console.error("usage: node tools/wire.js --validate <logs-dir> [<logs-dir> ...]");
    process.exit(2);
  }
  validate(directories).catch((error) => {
    console.error(error);
    process.exitCode = 1;
  });
}
